version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=454143665149.dkr.ecr.us-east-1.amazonaws.com/dockerimagetest
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $IMAGE_TAG
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker --version
      - docker ps
      - mvn clean install
      - docker tag codebuilddemo/awsdockerpoc $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"ECSDemoContainer","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json